version: '3.9'

services:
  ifound_portainer:
    ports:
      - 9000:9000
  ifound_mariadb:
    environment:
      - MARIADB_DATABASE=ifound_development
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - 53306:3306
  ifound_fastapi:
    environment:
      - MARIADB_DATABASE=ifound_development
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_HOST=ifound_mariadb
      - ENVIRONMENT=development
      - DATABASE_URL=mysql+pymysql://root:root@ifound_mariadb:3306/ifound_development
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - SECRET_KEY=boauw3enaeipb39
      - ALGORITHM=HS256
      - TRY_RELOAD_DUMP=True
    ports:
      - 8000:8000
  ifound_vue:
    environment:
      - VUE_APP_VERSION=0.0.1
      - VUE_APP_ENVIRONMENT=development
      - VUE_APP_API_URL=http://localhost:8000
      - HOST=0.0.0.0
      - PORT=8080
      - NODE_ENV=development #because devDependencies in package.json
      - ENV_MNT=development
    ports:
      - 8080:8080