"""Adição da coluna 'approved' nas tabelas payments e payments_audit

Revision ID: 4813163c1dfa
Revises: b0d348157d8e
Create Date: 2021-12-20 11:52:35.409585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4813163c1dfa'
down_revision = 'b0d348157d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('approved', sa.Boolean(), nullable=False))
    op.add_column('payments_audit', sa.Column('approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments_audit', 'approved')
    op.drop_column('payments', 'approved')
    # ### end Alembic commands ###
