"""Adição da coluna do ID da workspace StarkBank do usuário

Revision ID: 23a9ac2668b5
Revises: 003a21c377fb
Create Date: 2021-11-04 10:26:02.836809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a9ac2668b5'
down_revision = '003a21c377fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('starkbank_workspace_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_starkbank_workspace_id'), 'users', ['starkbank_workspace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_starkbank_workspace_id'), table_name='users')
    op.drop_column('users', 'starkbank_workspace_id')
    # ### end Alembic commands ###
