"""Mudanças nas tables de payments

Revision ID: 74cbf559a1fc
Revises: 4813163c1dfa
Create Date: 2021-12-22 09:48:12.037172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74cbf559a1fc'
down_revision = '4813163c1dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('payments_audit', 'approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('payments_audit', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_audit', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.alter_column('payments_audit', 'approved',
               existing_type=sa.String(length=255),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('payments', 'approved',
               existing_type=sa.String(length=255),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
