"""Adicionada coluna 'on_schedule' nas tabelas payments e payments_audit

Revision ID: a1ed29ec095e
Revises: fbd2dced187e
Create Date: 2022-08-09 13:29:04.860693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ed29ec095e'
down_revision = 'fbd2dced187e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('on_schedule', sa.Boolean(), nullable=True))
    op.add_column('payments_audit', sa.Column('on_schedule', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments_audit', 'on_schedule')
    op.drop_column('payments', 'on_schedule')
    # ### end Alembic commands ###
