"""Adicionada coluna 'paid' nas tabelas 'payments' e 'payments_audit'

Revision ID: 91640db89dbc
Revises: a1ed29ec095e
Create Date: 2022-08-10 15:29:45.706603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91640db89dbc'
down_revision = 'a1ed29ec095e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('paid', sa.Boolean(), nullable=False))
    op.add_column('payments_audit', sa.Column('paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments_audit', 'paid')
    op.drop_column('payments', 'paid')
    # ### end Alembic commands ###
