"""removidos campos do usuario nao usados

Revision ID: cddeb296878e
Revises: 91640db89dbc
Create Date: 2022-09-05 22:00:51.605462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cddeb296878e'
down_revision = '91640db89dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_audit')
    op.drop_index('transaction_key', table_name='transactions')
    op.drop_table('transactions')
    op.alter_column('users', 'birthday',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('ix_users_starkbank_workspace_id', table_name='users')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'city')
    op.drop_column('users', 'state')
    op.drop_column('users', 'quarter')
    op.drop_column('users', 'house_number')
    op.drop_column('users', 'address')
    op.drop_column('users', 'starkbank_workspace_id')
    op.drop_column('users', 'address_complement')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('address_complement', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('starkbank_workspace_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('house_number', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('quarter', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('state', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('city', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('zip_code', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('ix_users_starkbank_workspace_id', 'users', ['starkbank_workspace_id'], unique=False)
    op.alter_column('users', 'birthday',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('to_or_from', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('credit_or_debit', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('transaction_key', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transactions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index('transaction_key', 'transactions', ['transaction_key'], unique=False)
    op.create_table('payments_audit',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('approved', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pay_on_schedule', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='payments_audit_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
